 
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: cd-
  labels:
    workflows.argoproj.io/test: "true"
  annotations:
    workflows.argoproj.io/version: '>= 3.1.0'
spec:
  entrypoint: deploy
  templates:
    - name: deploy
      steps:
        - - name: app
            template: app
        - - name: test
            template: test            

    - name: app
      resource:
        action: create
        # successCondition and failureCondition are optional expressions which are
        # evaluated upon every update of the resource. If failureCondition is ever
        # evaluated to true, the step is considered failed. Likewise, if successCondition
        # is ever evaluated to true the step is considered successful. It uses kubernetes
        # label selection syntax and can be applied against any field of the resource
        # (not just labels). Multiple AND conditions can be represented by comma
        # delimited expressions. For more details, see:
        # https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/
        successCondition: status.succeeded > 0
        failureCondition: status.failed > 3
        manifest: |
          apiVersion: batch/v1
          kind: Job
          metadata:
            name: argocd-deploy-app
            namespace: default
            labels:
              app: argocd-deploy-app
          spec:            
            template:
              metadata:
                labels:
                  app: argocd-deploy-app
              spec:
                restartPolicy: OnFailure      
                containers:
                  - image: shashikanthvh/argocdappdeploy
                    imagePullPolicy: Always
                    name: argocddeployapp          
                    env:            
                      - name: ARGOTOKEN
                        value: "tQvrTkZoyuF6O-lx"
                      - name: APPNAME
                        value: "hw"
                      - name: APPREPO
                        value: "https://github.com/shashikanth-vh/helm-charts.git"
                      - name: APP
                        value: "example-app"      
                    ports:
                      - containerPort: 8082         
    - name: test
      resource:
        action: create
        # successCondition and failureCondition are optional expressions which are
        # evaluated upon every update of the resource. If failureCondition is ever
        # evaluated to true, the step is considered failed. Likewise, if successCondition
        # is ever evaluated to true the step is considered successful. It uses kubernetes
        # label selection syntax and can be applied against any field of the resource
        # (not just labels). Multiple AND conditions can be represented by comma
        # delimited expressions. For more details, see:
        # https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/
        successCondition: status.succeeded > 0
        failureCondition: status.failed > 3
        manifest: |
          apiVersion: batch/v1
          kind: Job
          metadata:
            name: app-test
            namespace: default
            labels:
              app: app-test
          spec:            
            template:
              metadata:
                labels:
                  app: app-test
              spec:
                restartPolicy: OnFailure      
                containers:
                  - image: shashikanthvh/robot
                    imagePullPolicy: Always
                    name: app-test          
                    env:            
                      - name: ARGOTOKEN
                        value: "tQvrTkZoyuF6O-lx"                      
                    ports:
                      - containerPort: 8082      
